"""Rendering — the console summary, the plan, the ledger, and two charts.

One rule governs everything here (ADR-0006): a euro figure never appears without
the sentence that says where it came from. A number that travels without its
provenance is a number that ends up in a steering deck as a fact.
"""

from __future__ import annotations

from pathlib import Path

from .capacity import size_capacity
from .catalog import Catalog, Platform
from .econ import databricks_run_eur_month, fabric_demand
from .rules import Plan

PLACEHOLDER = (
    "Every euro figure below is an **illustrative placeholder shaped like list "
    "pricing** — not a quote, not a rate card, not a client's contract. Replace "
    "`config/cost_model.yaml` with real numbers before any of it decides anything."
)

_LABEL = {
    Platform.FABRIC: "Fabric",
    Platform.DATABRICKS: "Databricks",
    Platform.STAY_ON_SYNAPSE: "stays on Synapse",
}

#: The console table is fixed-width, so it gets the short form. The long form is
#: what a reader of `reports/plan.md` sees, and there it should read as a sentence.
_SHORT = dict(_LABEL) | {Platform.STAY_ON_SYNAPSE: "Synapse"}


def console_summary(plan: Plan) -> str:
    cat = plan.catalog
    cap = plan.capacity
    lines: list[str] = []
    lines.append(
        f"ESTATE: {len(cat.workloads)} workloads · target region "
        f"{cat.platforms.target_region}"
    )
    lines.append("")
    header = (
        f"{'WORKLOAD':<23}{'KIND':<17}{'PLATFORM':<12}{'SURFACE':<21}"
        f"{'CU-H/MO':>9}{'€/MO':>9}  WHY"
    )
    lines.append(header)
    lines.append("-" * 118)
    for p in plan.placements:
        why = p.reason.split(".")[0].split(" — ")[0]
        if len(why) > 34:
            why = why[:31] + "..."
        lines.append(
            f"{p.workload_id:<23}{p.kind:<17}{_SHORT[p.platform]:<12}{p.surface:<21}"
            f"{p.fabric_cu_hours:>9,.0f}{p.run_eur_month:>9,.0f}  [{p.rule_id}] {why}"
        )
    lines.append("")

    counts = {pl: len(plan.by_platform(pl)) for pl in Platform}
    lines.append(
        "MIX   "
        + "  ".join(f"{_SHORT[pl].upper()}: {n}" for pl, n in counts.items() if n)
    )

    if cap.sku:
        lines.append(
            f"CAP   F{cap.sku} · {cap.sustained_cu:.1f} CU sustained of {cap.sku} "
            f"({cap.utilisation:.0%} used) · sized by the {cap.binding} allowance at "
            f"{cap.required_cu:.1f} CU required"
        )
    lines.append(
        f"RUN   €{plan.run_eur_month:,.0f}/month  "
        f"(capacity €{cap.total_eur:,.0f} · metered €{plan.databricks_run_eur:,.0f} · "
        f"platform overhead €{plan.platform_overhead_eur:,.0f})"
    )
    lines.append(
        f"MOVE  €{plan.migration_eur_month:,.0f}/month amortised over "
        f"{cat.costs.migration.amortise_months:.0f} months — "
        f"{plan.migration_eur_month / max(plan.total_eur_month, 1e-9):.0%} of the bill, and "
        f"almost identical on either platform"
    )
    lines.append(f"R8    {plan.step_review.reason}")

    stranded = plan.by_platform(Platform.STAY_ON_SYNAPSE)
    if stranded:
        lines.append(
            "HELD  "
            + ", ".join(p.workload_id for p in stranded)
            + " — no target survives its constraints"
        )
    return "\n".join(lines)


def _plan_markdown(plan: Plan) -> str:
    cat = plan.catalog
    cap = plan.capacity
    out: list[str] = []
    out.append("# The plan\n")
    out.append("*Generated by `make decide`. Do not edit by hand.*\n")
    out.append(PLACEHOLDER + "\n")

    out.append("## Where the estate lands\n")
    counts = {pl: len(plan.by_platform(pl)) for pl in Platform}
    out.append("| Destination | Workloads |")
    out.append("|---|---|")
    for pl, n in counts.items():
        if n:
            out.append(f"| {_LABEL[pl]} | {n} |")
    out.append("")

    out.append("## The capacity\n")
    if cap.sku:
        out.append(
            f"**F{cap.sku}** — {cap.sustained_cu:.1f} CU sustained against a purchased "
            f"{cap.sku} CU, so **{cap.utilisation:.0%} of what is paid for is used** and "
            f"{cap.headroom_cu:.1f} CU sit idle.\n"
        )
        out.append(
            f"The rung was chosen by the **{cap.binding}** allowance: "
            f"{cap.required_cu:.1f} CU required after headroom, against "
            f"{cap.sustained_cu:.1f} CU of raw sustained demand "
            f"({cap.interactive_cu:.1f} CU of it interactive). Fabric smooths and then "
            f"throttles, so a capacity planned to its ceiling is a capacity that "
            f"throttles interactive users while background jobs catch up — which is why "
            f"the allowances exist and why the sized number is larger than the demand.\n"
        )
    out.append(f"**R8 · step-boundary review.** {plan.step_review.reason}.\n")

    out.append("## The bill\n")
    out.append("| Line | €/month | Note |")
    out.append("|---|---:|---|")
    out.append(
        f"| Fabric capacity (F{cap.sku}) | {cap.monthly_eur:,.0f} | "
        f"pre-paid; carries {len(plan.by_platform(Platform.FABRIC))} workloads |"
    )
    out.append(f"| Fabric storage | {cap.storage_eur:,.0f} | OneLake + Eventhouse hot cache |")
    out.append(
        f"| Databricks metered | {plan.databricks_run_eur:,.0f} | "
        f"{len(plan.by_platform(Platform.DATABRICKS))} workloads, straight-line |"
    )
    out.append(
        f"| Platform overhead | {plan.platform_overhead_eur:,.0f} | "
        f"paid per platform operated, not per workload |"
    )
    out.append(f"| **Run, total** | **{plan.run_eur_month:,.0f}** | recurs forever |")
    out.append(
        f"| Migration, amortised | {plan.migration_eur_month:,.0f} | over "
        f"{cat.costs.migration.amortise_months:.0f} months |"
    )
    out.append(f"| **Total** | **{plan.total_eur_month:,.0f}** | |")
    out.append("")
    share = plan.migration_eur_month / max(plan.total_eur_month, 1e-9)
    out.append(
        f"The migration is **{share:.0%} of the bill over this horizon, and it is very "
        f"nearly the same number on either platform** — it differs only where a T-SQL "
        f"surface would have to be rewritten rather than moved. The platform choice "
        f"moves the smaller half. That does not make it unimportant: run cost is the "
        f"half that never stops. But a Fabric-versus-Databricks argument that never says "
        f"this out loud is an argument with a missing premise.\n"
    )

    out.append("## Every workload, with the reason in the row\n")
    out.append("| Workload | Kind | → | Surface | CU-h/mo | €/mo | Rule | Why |")
    out.append("|---|---|---|---|---:|---:|---|---|")
    for p in plan.placements:
        out.append(
            f"| `{p.workload_id}` | {p.kind} | {_LABEL[p.platform]} | {p.surface} | "
            f"{p.fabric_cu_hours:,.0f} | {p.run_eur_month:,.0f} | {p.rule_id} | {p.reason} |"
        )
    out.append("")
    out.append(
        "A Fabric workload showing **€0** is not free. It is riding capacity the estate "
        "already pays for, and the capacity is billed once in the table above. That is "
        "the whole difference between a pre-paid capacity and a meter, and it is why "
        "these two columns cannot be added up per row.\n"
    )

    out.append("## What was ruled out, and by what\n")
    out.append(
        "Constraints eliminate; economics chooses. Everything in this section happened "
        "before any price was compared.\n"
    )
    for p in plan.placements:
        if not p.eliminated:
            continue
        out.append(f"**`{p.workload_id}`** — {p.name}")
        for platform, why in p.eliminated.items():
            out.append(f"- {_LABEL[platform]}: {why}")
        out.append("")

    return "\n".join(out)


def _chart_capacity(plan: Plan, path: Path) -> Path:
    """The step function against the straight line.

    The one picture worth having. Everything else in this repo is an elaboration
    of the gap between these two shapes.
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    cat = plan.catalog
    c = cat.costs.fabric
    skus = sorted(c.skus)
    rate = c.effective_eur_per_cu_hour * cat.costs.hours_per_month

    all_fabric = size_capacity(cat.workloads, cat)
    top = max(all_fabric.required_cu, plan.capacity.required_cu) * 1.35

    # One horizontal segment per rung, over the range of demand that rung serves.
    # Consecutive segments share an x, which is what draws the riser between them.
    xs: list[float] = []
    ys: list[float] = []
    prev = 0.0
    highest = 0.0
    for sku in skus:
        if prev >= top:
            break
        xs.extend([prev, min(float(sku), top)])
        ys.extend([sku * rate, sku * rate])
        highest = sku * rate
        prev = float(sku)

    fig, ax = plt.subplots(figsize=(9.5, 5.4))
    ax.plot(xs, ys, linewidth=2.4, color="#1f6feb", label="Fabric capacity — a step function")

    # The metered alternative on the same axis, drawn as a straight line through the
    # estate's own point. The honest claim is "metered is linear", not "metered is
    # exactly this" — the conversion between a CU and a DBU is the least defensible
    # number in the repo (see config/cost_model.yaml).
    fab_cu = (
        sum(fabric_demand(w, cat).compute_units for w in cat.workloads)
        / cat.costs.hours_per_month
    )
    db_all = sum(databricks_run_eur_month(w, cat) for w in cat.workloads)
    if fab_cu > 0:
        slope = db_all / fab_cu
        ax.plot(
            [0, top],
            [0, slope * top],
            linewidth=2.0,
            color="#d97706",
            linestyle="--",
            label="Databricks metered — a straight line",
        )

    ax.set_ylim(0, highest * 1.18)
    ax.set_xlim(0, top)

    req = plan.capacity.required_cu
    sku_eur = (plan.capacity.sku or 0) * rate
    ax.axvline(req, color="#16a34a", linewidth=1.4, linestyle=":")
    # The rung the plan actually sits on, marked — the riser above it is the one it
    # avoided, and without a marker the two read as the same point.
    ax.plot([req], [sku_eur], "o", color="#16a34a", markersize=7, zorder=5)
    ax.annotate(
        f"this plan · F{plan.capacity.sku}\n{req:.1f} CU required, "
        f"{plan.capacity.utilisation:.0%} of the rung used",
        xy=(req, sku_eur),
        xytext=(req * 0.06, highest * 1.05),
        fontsize=9,
        color="#166534",
        arrowprops={"arrowstyle": "->", "color": "#16a34a", "linewidth": 1.0},
    )
    ax.axvline(all_fabric.required_cu, color="#9333ea", linewidth=1.2, linestyle=":")
    ax.plot(
        [all_fabric.required_cu],
        [(all_fabric.sku or 0) * rate],
        "o",
        color="#9333ea",
        markersize=7,
        zorder=5,
    )
    ax.annotate(
        f"everything on Fabric · F{all_fabric.sku}\n{all_fabric.required_cu:.1f} CU — "
        f"one rung higher, for the\nsake of the workloads R7 declined",
        xy=(all_fabric.required_cu, (all_fabric.sku or 0) * rate),
        xytext=(all_fabric.required_cu * 0.42, highest * 0.62),
        fontsize=9,
        color="#6b21a8",
        arrowprops={"arrowstyle": "->", "color": "#9333ea", "linewidth": 1.0},
    )

    ax.set_xlabel("sustained capacity required (CU, after headroom)")
    ax.set_ylabel(f"€/month ({cat.costs.currency}, illustrative)")
    ax.set_title("A step function against a straight line")
    ax.grid(alpha=0.25)
    ax.legend(loc="lower right", fontsize=9)
    fig.text(
        0.5,
        0.005,
        "Illustrative placeholder pricing from config/cost_model.yaml — not a quote.",
        ha="center",
        fontsize=7.5,
        color="#6b7280",
    )
    fig.tight_layout(rect=(0, 0.03, 1, 1))
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def _chart_mix(plan: Plan, path: Path) -> Path:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    kinds = ["dedicated_sql", "serverless_view", "spark_notebook", "pipeline", "stream"]
    order = [Platform.FABRIC, Platform.DATABRICKS, Platform.STAY_ON_SYNAPSE]
    colors = {
        Platform.FABRIC: "#1f6feb",
        Platform.DATABRICKS: "#d97706",
        Platform.STAY_ON_SYNAPSE: "#6b7280",
    }

    fig, ax = plt.subplots(figsize=(9, 4.4))
    bottom = [0.0] * len(kinds)
    for pl in order:
        vals = [
            float(sum(1 for p in plan.placements if p.platform is pl and p.kind == k))
            for k in kinds
        ]
        if not any(vals):
            continue
        ax.bar(kinds, vals, bottom=bottom, label=_LABEL[pl], color=colors[pl])
        bottom = [b + v for b, v in zip(bottom, vals, strict=True)]

    ax.set_ylabel("workloads")
    ax.set_title("The answer is 'both', and the split is not by preference")
    ax.legend(fontsize=9)
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def write_all(plan: Plan, reports_dir: Path | None = None) -> list[Path]:
    out = Path(reports_dir) if reports_dir else Path("reports")
    out.mkdir(parents=True, exist_ok=True)
    written = [out / "plan.md"]
    (out / "plan.md").write_text(_plan_markdown(plan), encoding="utf-8")
    written.append(_chart_capacity(plan, out / "capacity-step.png"))
    written.append(_chart_mix(plan, out / "mix.png"))
    return written


def explain(plan: Plan, workload_id: str, cat: Catalog) -> str:
    """Everything the engine knows about one workload, including the roads not taken."""
    match = [p for p in plan.placements if p.workload_id == workload_id]
    if not match:
        known = ", ".join(p.workload_id for p in plan.placements)
        raise KeyError(f"unknown workload {workload_id!r}; known: {known}")
    p = match[0]
    w = cat.workload(workload_id)

    lines = [f"{p.workload_id} — {p.name}"]
    lines.append(f"  kind       {p.kind} · {w.consumer} · {w.latency_class}")
    lines.append(f"  decision   {_LABEL[p.platform]} / {p.surface}  (rule {p.rule_id})")
    lines.append(f"  because    {p.reason}")
    if p.eliminated:
        lines.append("  ruled out")
        for platform, why in p.eliminated.items():
            lines.append(f"    - {_LABEL[platform]}: {why}")
    fd = fabric_demand(w, cat)
    lines.append("  demand")
    lines.append(
        f"    Fabric      {fd.compute_units:,.0f} CU-h/mo "
        f"(compute {fd.from_compute:,.0f} · scan {fd.from_scan:,.0f} · "
        f"events {fd.from_events:,.0f}) + €{fd.storage_eur_month:,.0f}/mo storage"
    )
    lines.append(
        f"    Databricks  €{p.databricks_eur_month:,.0f}/mo metered, standalone and true"
    )
    if p.platform is Platform.FABRIC:
        lines.append(
            f"    marginal    €{p.marginal_eur:,.0f}/mo — what it actually added to the "
            f"capacity, which is the only Fabric number that means anything per workload"
        )
    lines.append(f"  migration  €{p.migration_eur_month:,.0f}/mo amortised")
    for n in p.notes:
        lines.append(f"  note       {n}")
    if p.flags:
        lines.append(f"  flags      {', '.join(sorted(set(p.flags)))}")
    return "\n".join(lines)
