"""Run both simulations and write the honest account of what they mean.

The report this produces is deliberately as long on caveats as on results. A
simulation that reports only its findings is a simulation being used to win an
argument rather than to settle one (ADR-0001).
"""

from __future__ import annotations

from pathlib import Path

from .batch import run_batch
from .streaming import MICRO_BATCH_S, WATERMARK_S, WINDOW_S, run_streaming


def _arrow_builder():
    """Return (build_table, write_deltalake, DeltaTable), or None if unavailable.

    `deltalake` 1.x dropped its pyarrow dependency in favour of `arro3`, and 0.x
    predates it. Both are supported here rather than pinning one, because the point
    of the extra is to be easy to install, not to be a version negotiation.
    """
    try:
        from deltalake import DeltaTable, write_deltalake
    except ImportError:
        return None

    try:
        from arro3.core import Array, DataType, Field, Schema, Table

        def build(windows: list[int], cents: list[int]):
            schema = Schema(
                [Field("window", DataType.int64()), Field("cents", DataType.int64())]
            )
            return Table.from_arrays(
                [Array(windows, DataType.int64()), Array(cents, DataType.int64())],
                schema=schema,
            )

        return build, write_deltalake, DeltaTable
    except ImportError:
        pass

    try:
        import pyarrow as pa

        def build(windows: list[int], cents: list[int]):
            return pa.table(
                {
                    "window": pa.array(windows, pa.int64()),
                    "cents": pa.array(cents, pa.int64()),
                }
            )

        return build, write_deltalake, DeltaTable
    except ImportError:
        return None


def _delta_sink(rows: list[dict], out: Path) -> str:
    """Materialise the streaming sink as a real Delta table, if `deltalake` is here.

    Optional on purpose (ADR-0001): the default path must run with nothing
    installed but Python. When it is available the point is small but real — the
    sink gets an actual transaction log, so the claim "the streaming shape lands
    in Delta" is a file on disk rather than a sentence in a README.
    """
    build = _arrow_builder()
    if build is None:
        return (
            "skipped — `deltalake` is not installed. `make delta` (or "
            "`pip install -e \".[dev,delta]\"`) materialises the sink as a real Delta "
            "table with a transaction log."
        )
    write_deltalake, DeltaTable = build[1], build[2]

    path = out / "payments_by_window"
    table = build[0](
        [r["window"] for r in rows],
        [r["streaming"] for r in rows],
    )
    write_deltalake(str(path), table, mode="overwrite")
    # A second write, so there is a version 1 and the time-travel claim is testable.
    write_deltalake(str(path), table, mode="overwrite")
    dt = DeltaTable(str(path))
    return (
        f"written to `{path}` as a Delta table — {len(rows)} rows, version "
        f"{dt.version()}, with a transaction log on disk. No Spark and no JVM were "
        f"involved, which is worth knowing but is not what Databricks is being "
        f"bought for."
    )


def run(reports_dir: Path | None = None, data_dir: Path | None = None) -> Path:
    reports = Path(reports_dir) if reports_dir else Path("reports")
    data = Path(data_dir) if data_dir else Path("data") / "delta"
    reports.mkdir(parents=True, exist_ok=True)
    data.mkdir(parents=True, exist_ok=True)

    batch = run_batch()
    stream, rows = run_streaming()
    delta_note = _delta_sink(rows, data)

    eur = lambda c: f"€{c / 100:,.2f}"  # noqa: E731 — a formatter, not a function

    out: list[str] = []
    out.append("# The simulation\n")
    out.append("*Generated by `make simulate`. Do not edit by hand.*\n")
    out.append(
        "Two of the eliminations in the rule set are the kind that get nodded through "
        "in a design review. Both are executed here instead.\n"
    )

    # ---- R3 ------------------------------------------------------------------
    out.append("## R3 — an ingestion-time engine is not a cheaper event-time engine\n")
    out.append(
        f"The same {stream.windows} windows of payment traffic, from the same source, "
        f"down both shapes. {stream.late_events:,} deliveries arrived late — a client "
        f"went offline and came back — and {stream.duplicates_counted_by_eventhouse:,} "
        f"arrived twice, because at-least-once delivery did its job.\n"
    )
    out.append("| | Total settled | Per-window error vs truth |")
    out.append("|---|---:|---:|")
    out.append(f"| Ground truth (distinct events, by event time) | {eur(stream.truth_total_cents)} | — |")
    out.append(
        f"| **Eventhouse shape** (append, by ingestion time) | "
        f"{eur(stream.eventhouse_total_cents)} | **{stream.eventhouse_error_pct:.2f}%** |"
    )
    out.append(
        f"| **Structured Streaming shape** (event time, watermark, MERGE) | "
        f"{eur(stream.streaming_total_cents)} | **{stream.streaming_error_pct:.2f}%** |"
    )
    out.append("")
    over = stream.eventhouse_total_cents - stream.truth_total_cents
    out.append(
        "Two separate failures, and they are worth separating because they have "
        "different fixes.\n"
    )
    out.append(
        f"1. **The total is wrong by {eur(over)}** — every redelivered payment was "
        f"counted twice. An append-only sink has no key to conflict on, so there is "
        f"nowhere for the second delivery to be recognised.\n"
    )
    out.append(
        f"2. **The windows are wrong by {stream.eventhouse_error_pct:.2f}% even where "
        f"the total is right** — a payment that happened at 09:58 and arrived at 10:44 "
        f"is counted in the 10:40 window. Nothing is lost; everything is in the wrong "
        f"bucket. This is the failure that survives a reconciliation of totals and then "
        f"surfaces as a dispute about a specific day.\n"
    )
    out.append(
        f"The streaming shape restated **{stream.restatements:,} windows** it had "
        f"already written, using a {WATERMARK_S // 60}-minute watermark over "
        f"{WINDOW_S // 60}-minute windows in {MICRO_BATCH_S // 60}-minute micro-batches, "
        f"and finished exactly on the truth.\n"
    )
    out.append(
        "**This is not a defect in the ingestion-time engine.** It is doing precisely "
        "what an append-only telemetry store should do, on a workload that needed "
        "something else. Two workloads in the estate — device telemetry and clickstream "
        "— want exactly this behaviour and are assigned to it. The payment ledger is "
        "not one of them, and R3 is what keeps it from being routed there because it "
        "was also a stream.\n"
    )
    out.append(f"Sink: {delta_note}\n")

    # ---- R2 ------------------------------------------------------------------
    out.append("## R2 — what a multi-table transaction is actually buying\n")
    out.append(
        f"The same {batch.rows_loaded:,}-row staging batch, loaded into the same fact "
        f"and the same customer aggregate, in two shapes. Then the load is killed "
        f"between the two writes, which is what actually happens at 03:00.\n"
    )
    out.append("| Shape | Killed mid-load, then retried | Aggregate agrees with the fact |")
    out.append("|---|---|---|")
    out.append(
        f"| Warehouse, one multi-table transaction | rolled back, retry clean | "
        f"{'yes' if batch.warehouse_consistent_with_transaction else 'no'} |"
    )
    out.append(
        f"| The same load, ported without transactions | fact written, aggregate not | "
        f"**no — {batch.torn_customers:,} customers torn** |"
    )
    out.append(
        f"| Lakehouse, partition replace + recompute | re-run, converged | "
        f"{'yes' if batch.lakehouse_consistent_after_retry else 'no'} |"
    )
    out.append("")
    out.append(
        f"Both correct shapes agree on the answer — parity check "
        f"**{'passes' if batch.parity else 'FAILS'}**, "
        f"{eur(batch.warehouse_total_cents)} either way. What differs is *how* they stay "
        f"correct, and that is the part that does not port. The middle row is what a "
        f"lift-and-shift of a transactional load onto a platform without multi-table "
        f"transactions produces: {batch.torn_customers:,} customers whose stored "
        f"aggregate disagrees with the fact beneath it, with nothing in either table "
        f"saying so. Nobody would ship that deliberately. It is what happens when a "
        f"migration plan treats the T-SQL surface as a dialect difference.\n"
    )
    out.append(
        "The lakehouse shape is not worse — it is a different consistency model, and "
        "arguably a better one for a batch estate. It is simply not the same code, and "
        "R2 prices it as a rewrite rather than a move.\n"
    )

    # ---- the honesty section -------------------------------------------------
    out.append("## What these measurements do and do not mean\n")
    out.append(
        "DuckDB stands in for both engines. Everything above is therefore a statement "
        "about **semantics**, and nothing above is a statement about **performance**.\n"
    )
    out.append("**Survives the substitution — these are real findings:**\n")
    out.append(
        "- Ingestion-time bucketing misplaces late events, and no amount of capacity "
        "fixes it.\n"
        "- An append-only sink cannot deduplicate; a keyed MERGE sink can.\n"
        "- A watermark bounds how late is too late, and dropping past it is a decision "
        "that has to be made explicitly.\n"
        "- Multi-table transactional maintenance and idempotent partition replacement "
        "are different designs with different failure behaviour.\n"
    )
    out.append("**Does not survive it — do not quote any of this:**\n")
    out.append(
        "- Throughput, latency, cost per query, cluster or capacity sizing. Not "
        "measured, not inferable.\n"
        "- Fabric Eventhouse and Databricks Structured Streaming are not in this "
        "process. Their real behaviour under load, their operational surface and their "
        "actual guarantees must be checked against current vendor documentation.\n"
        "- The Delta table written above is `deltalake` on a laptop, not Databricks. "
        "The format is real; the runtime is not.\n"
    )

    path = reports / "simulation.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {path}")
    print(
        f"  R3  eventhouse off by {stream.eventhouse_error_pct:.2f}% per window "
        f"and {eur(stream.eventhouse_total_cents - stream.truth_total_cents)} in total; "
        f"streaming exact after {stream.restatements:,} restatements"
    )
    print(
        f"  R2  transactional load rolls back clean; the same load without transactions "
        f"leaves {batch.torn_customers:,} torn customers; parity "
        f"{'holds' if batch.parity else 'FAILS'}"
    )
    return path
